version: "3"
services:
  spark:
    container_name: spark
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workdir:/workdir
    networks:
      - minikube

networks:
  minikube:
    name: minikube
    external: true
